/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejsfamilyhome;


import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;

import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFPrintSetup;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.usermodel.HeaderFooter;

import org.apache.poi.hssf.util.CellRangeAddress;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Footer;
import org.apache.poi.ss.usermodel.Header;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.tools.ant.types.resources.selectors.Date;

/**
 *
 * @author Gezelle
 */
public class MedicationRecord extends javax.swing.JFrame {

    /**
     * Creates new form MedicationList
     */
    
    
    public MedicationRecord() {
        initComponents();
         myComboBox();
         //dateOfBirth();
    }
    
     Connection con = MyDBConnection.getConnection();
     
     
     static String selectedClient;
static String[] name;
static String lastName;
static String firstName;
static java.sql.Date dob;
static int key;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Current Medications");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Patient Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Medication Brand Name", "Dose", "Frequency", "RX Number", "RX Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(140);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jButton1.setText("Print MAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         try {
           
            ResultSet rs=null;
            PreparedStatement stmt=null;
            String selectedClient = jComboBox1.getSelectedItem().toString();
             System.out.println(selectedClient);
           name = selectedClient.split("\\,");
           lastName = name[0];
           firstName = name[1];        
                

           stmt= con.prepareStatement("select MedicationBrandName,  MedicationDose, Frequency, RXNumber, RXDate, ClientKey from client \n" +
"join medication on client.ClientKey = medication.Client_ClientKey \n" +
//"join medicationschedule_has_medication on medicationschedule_has_medication.Medication_MedicationKey=medication.MedicationKey\n" +
//"join medicationschedule on medicationschedule.ScheduleId=medicationschedule_has_medication.MedicationSchedule_ScheduleId\n" +
" where LastName='" + lastName + "' and FirstName='" + firstName.trim() + "' order by MedicationBrandName");
            rs = stmt.executeQuery();
            
            
          
            jTable2.getTableHeader().resizeAndRepaint();
            
            // Removing Previous Data
            while (jTable2.getRowCount() > 0) {
                ((DefaultTableModel) jTable2.getModel()).removeRow(0);
            }
            
            
            //Creating Object []rowData for jTable's Table Model
            
            int columns = rs.getMetaData().getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++) {
                    row[i - 1] = rs.getObject(i); // 1
                }
                ((DefaultTableModel) jTable2.getModel()).insertRow(rs.getRow() - 1,row);
                key = rs.getInt(6);
            } 
           System.out.println(key);
        } 
          
          catch (HeadlessException | SQLException e) {
            System.err.println(e);
            //System.exit(1);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try {
                       
                        PreparedStatement psmnt = null;
                        Statement st = con.createStatement();
                        String query = "";
                        query = "select MedicationBrandName, MedicationDose, Frequency, RXNumber, RXDate, LastName, FirstName  from client\n" +
"join medication on client.ClientKey = medication.Client_ClientKey \n" +
" where LastName='" + lastName + "' and FirstName='" + firstName.trim() + "' order by MedicationBrandName";                      
                       Cell cell;
                        ResultSet rs = st.executeQuery(query);             
                        HSSFWorkbook wb = new HSSFWorkbook();
                        HSSFSheet sheet = wb.createSheet("Excel Sheet");
                        sheet.getPrintSetup().setLandscape(true);
                        sheet.getPrintSetup().setPaperSize(HSSFPrintSetup.LETTER_PAPERSIZE); 
                        sheet.setMargin(Sheet.LeftMargin, 0.1);
                         sheet.setMargin(Sheet.RightMargin, 0.1);
                         sheet.setMargin(Sheet.TopMargin, 1.0);
                          sheet.setMargin(Sheet.BottomMargin, 1.0);
                         
                         sheet.setRepeatingRows(CellRangeAddress.valueOf("1:2"));
                        
                         
                          
                   int index = 2;         
                          
                         
                                              
                         HSSFCellStyle txtStyle = (HSSFCellStyle)wb.createCellStyle();
                         HSSFFont txtFont = (HSSFFont)wb.createFont();
                         txtFont.setFontHeightInPoints((short)8);
                         txtStyle.setFont(txtFont);
                         
                         HSSFCellStyle styleA = wb.createCellStyle();
                        styleA.setAlignment(HSSFCellStyle.ALIGN_CENTER);
                        styleA.setVerticalAlignment( 
                        HSSFCellStyle.VERTICAL_CENTER);
                        styleA.setBorderBottom(HSSFCellStyle.BORDER_THIN);
                         styleA.setBorderTop(HSSFCellStyle.BORDER_THIN);
                          styleA.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                        styleA.setBorderRight(HSSFCellStyle.BORDER_THIN);
                        
                         HSSFCellStyle styleB = wb.createCellStyle();
                        styleB.setAlignment(HSSFCellStyle.ALIGN_CENTER);
                        styleB.setVerticalAlignment( 
                        HSSFCellStyle.VERTICAL_CENTER);
                        styleB.setBorderBottom(HSSFCellStyle.BORDER_THIN);
                         styleB.setBorderTop(HSSFCellStyle.BORDER_THIN);
                          styleB.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                        styleB.setBorderRight(HSSFCellStyle.BORDER_THIN);
                         styleB.setFillForegroundColor(HSSFColor.GREY_40_PERCENT.index);
                        styleB.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
                         
                       
                        
                        
                        
                        
                        HSSFRow row1 = sheet.createRow((short)1);
                        cell = row1.createCell((short)0);
                        cell.setCellValue("ROUTINE MEDICATIONS");
                       cell.setCellStyle(txtStyle);
                       
                       // cell.setCellStyle(txtStyle);
                        cell = row1.createCell((short)1);
                        cell.setCellValue("HOUR");
                        cell.setCellStyle(txtStyle);
                        sheet.setColumnWidth(1, 1200);
                        
                        HSSFRow row32 = sheet.createRow((short)32);
                           HSSFRow row33 = sheet.createRow((short)33);
                              HSSFRow row34 = sheet.createRow((short)34);
                        cell = row32.createCell((short)0);
                        cell.setCellValue("Name");
                        cell.setCellStyle(styleB);
                       
                       cell = row32.createCell((short)1);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                       cell = row32.createCell((short)2);
                        cell.setCellValue("Name"); 
                        cell.setCellStyle(styleB);
                       cell = row32.createCell((short)10);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                        cell = row32.createCell((short)12);
                        cell.setCellValue("Name");  
                        cell.setCellStyle(styleB);
                       cell = row32.createCell((short)20);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                        cell = row32.createCell((short)22);
                        cell.setCellValue("Name");  
                        cell.setCellStyle(styleB);
                       cell = row32.createCell((short)30);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                       for(int i=0;i<33;i++){
                       cell = row33.createCell((short)i); 
                       cell.setCellStyle(styleA);
                        cell = row34.createCell((short)i); 
                        cell.setCellStyle(styleA);
                       if((i==0) || (i==1) || (i==2) ||(i==12) ||(i==10) || (i==20) || (i==22) || (i==30))
                       continue;
                       
                       cell = row32.createCell((short)i);                    
                       cell.setCellStyle(styleB);
                       }
                       
                       for(int i=32; i<35; i++) {
                        sheet.addMergedRegion(new CellRangeAddress(i,i, 2, 9  ));                        
                        sheet.addMergedRegion(new CellRangeAddress(i,i,10,11));
                        sheet.addMergedRegion(new CellRangeAddress(i,i,12,19));
                         sheet.addMergedRegion(new CellRangeAddress(i,i,20,21));
                         sheet.addMergedRegion(new CellRangeAddress(i,i,22,29));                       
                         sheet.addMergedRegion(new CellRangeAddress(i,i,30,32));
                        
                       }
                        
                        dateOfBirth();
                        //Add Header and Footer
     Header header = sheet.getHeader();
    header.setLeft("Resident: " + lastName + " " + firstName);
    header.setCenter("Date of Birth: " + dob);
   Footer foot = sheet.getFooter();
   foot.setRight("Date Printed: " +  HeaderFooter.date());
   foot.setLeft("page " + HeaderFooter.page() + " of " + HeaderFooter.numPages());
   
                        
                        for(int i=2; i<33; i++) {
                            cell = row1.createCell((short) i);
                              cell.setCellValue(i-1);  
                                cell.setCellStyle(txtStyle);
                              sheet.setColumnWidth(i, 700);
                         }
                        

    
                        
                       // rowhead.createCell((short) 2).setCellValue("Dose");
                       // rowhead.createCell((short) 3).setCellValue("Frequency");
                       // rowhead.createCell((short) 4).setCellValue("RX Number");
                       //  rowhead.createCell((short) 5).setCellValue("RX Date"); 

                      
                          CreationHelper createHelper = wb.getCreationHelper();
                         
                      //   CellStyle cellStyle = wb.createCellStyle();
                        // cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("m/d/yy"));
                         // cellStyle.setBorderRight(HSSFCellStyle.BORDER_THIN);
                          CellStyle style2 = wb.createCellStyle();
                         style2.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                         style2.setFont(txtFont);
                         CellStyle style3 = wb.createCellStyle();
                         style3.setBorderRight(HSSFCellStyle.BORDER_THIN);
                         style3.setFont(txtFont);
                         CellStyle style4 = wb.createCellStyle();
                         style4.setBorderTop(HSSFCellStyle.BORDER_THIN);
                          style4.setFont(txtFont);
                          CellStyle style5 = wb.createCellStyle();
                         style5.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                          style5.setBorderTop(HSSFCellStyle.BORDER_THIN);
                           style5.setFont(txtFont);
                           CellStyle style6 = wb.createCellStyle();
                         style6.setBorderRight(HSSFCellStyle.BORDER_THIN);
                                  style6.setBorderTop(HSSFCellStyle.BORDER_THIN);
                                   style6.setFont(txtFont);
                                  CellStyle style7 = wb.createCellStyle();
                         style7.setBorderRight(HSSFCellStyle.BORDER_THIN);
                         style7.setBorderBottom(HSSFCellStyle.BORDER_THIN);
                          style7.setFont(txtFont);
                         CellStyle style8 = wb.createCellStyle();
                         style8.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                         style8.setBorderBottom(HSSFCellStyle.BORDER_THIN);
                         style8.setDataFormat(createHelper.createDataFormat().getFormat("m/d/yy"));
                         style8.setFont(txtFont);
                          CellStyle style9 = wb.createCellStyle();
                         style9.setBorderLeft(HSSFCellStyle.BORDER_THIN);
                         style9.setBorderBottom(HSSFCellStyle.BORDER_THIN);
                         style9.setBorderRight(HSSFCellStyle.BORDER_THIN);
                         style9.setBorderTop(HSSFCellStyle.BORDER_THIN);
                                   style9.setFont(txtFont);
                       
                         
                             
                             
                             
                        while (rs.next()) {
                              HSSFRow row = sheet.createRow((short) index);
                              HSSFRow row2 = sheet.createRow((short) index + 1);
                               HSSFRow row3 = sheet.createRow((short) index + 2);
                                HSSFRow row4 = sheet.createRow((short) index + 3);
                                HSSFRow row5 = sheet.createRow((short) index + 4);
                                
                                
                               cell = row.createCell((short) 0);
                                cell.setCellStyle(style5);                                
                                cell.setCellValue(rs.getString(1));
                                 
                                cell = row.createCell((short)1);
                                cell.setCellStyle(style6);
                                
                                for(int i=1; i<33; i++) {
                              cell = row.createCell((short) i);
                                cell.setCellStyle(style9); 
                         }
                              
                                
                                
                                cell = row2.createCell((short) 0);
                                cell.setCellValue(rs.getString(2));
                                 cell.setCellStyle(style2);
                                 
                                  cell = row2.createCell((short)1);
                                cell.setCellStyle(style3);
                                  for(int i=1; i<33; i++) {
                              cell = row2.createCell((short) i);
                                cell.setCellStyle(style9); 
                         }
                                
                                
                                
                                  cell = row3.createCell((short) 0);
                                cell.setCellValue(rs.getString(3));
                                cell.setCellStyle(style2);
                                 cell = row3.createCell((short)1);
                                cell.setCellStyle(style3);
                                
                                 for(int i=1; i<33; i++) {
                              cell = row3.createCell((short) i);
                                cell.setCellStyle(style9); 
                         }
                                
                                 cell = row4.createCell((short) 0);
                                cell.setCellValue(rs.getString(4));
                                cell.setCellStyle(style2);
                                
                               
                                  for(int i=1; i<33; i++) {
                              cell = row4.createCell((short) i);
                                cell.setCellStyle(style9); 
                         }
                                 
                              
                                
                                
                                cell = row5.createCell((short) 0);
                                cell.setCellValue(rs.getDate(5));
                                cell.setCellStyle(style8);
                              
                              //  cell.setCellValue("date");
                              
                                
                                 cell = row5.createCell((short)1);
                                  
                                cell.setCellStyle(style7);
                                 for(int i=1; i<33; i++) {
                              cell = row5.createCell((short) i);
                                cell.setCellStyle(style9); 
                         }
                             
                                 index = index+5;
                                 
                           if(index==32){
                              index = index+5;
                           
                           }
                           
                             if(index==67){
                              index = index+5;
                           
                           }
                                 
                              if(index > 36) {
                             HSSFRow row67 = sheet.createRow((short)67);
                           HSSFRow row68 = sheet.createRow((short)68);
                              HSSFRow row69 = sheet.createRow((short)69);
                        cell = row67.createCell((short)0);
                        cell.setCellValue("Name");
                        cell.setCellStyle(styleB);
                       
                       cell = row67.createCell((short)1);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                       cell = row67.createCell((short)2);
                        cell.setCellValue("Name"); 
                        cell.setCellStyle(styleB);
                       cell = row67.createCell((short)10);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                        cell = row67.createCell((short)12);
                        cell.setCellValue("Name");  
                        cell.setCellStyle(styleB);
                       cell = row67.createCell((short)20);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                        cell = row67.createCell((short)22);
                        cell.setCellValue("Name");  
                        cell.setCellStyle(styleB);
                       cell = row67.createCell((short)30);
                       cell.setCellValue("initial");
                       cell.setCellStyle(styleB);
                       
                       for(int i=0;i<33;i++){
                       cell = row68.createCell((short)i); 
                       cell.setCellStyle(styleA);
                        cell = row69.createCell((short)i); 
                        cell.setCellStyle(styleA);
                       if((i==0) || (i==1) || (i==2) ||(i==12) ||(i==10) || (i==20) || (i==22) || (i==30))
                       continue;                       
                       cell = row67.createCell((short)i);                    
                       cell.setCellStyle(styleB);
                       }
                       
                       for(int i=67; i<70; i++) {
                        sheet.addMergedRegion(new CellRangeAddress(i,i, 2, 9  ));                        
                        sheet.addMergedRegion(new CellRangeAddress(i,i,10,11));
                        sheet.addMergedRegion(new CellRangeAddress(i,i,12,19));
                         sheet.addMergedRegion(new CellRangeAddress(i,i,20,21));
                         sheet.addMergedRegion(new CellRangeAddress(i,i,22,29));                       
                         sheet.addMergedRegion(new CellRangeAddress(i,i,30,32));
                        
                       }
                        }
                       
                              
                               sheet.autoSizeColumn(0);
                              
                        }

                           System.out.println("Writing Data");
                              
                      
                        FileOutputStream fileOut = new FileOutputStream("C:/Users/Gezelle/Documents/MAR/" +lastName + "_" +firstName + ".xls");
                        wb.write(fileOut);
                        fileOut.close();
                        System.out.println("Data is saved in excel file.");
                        rs.close();
                         try {
            Desktop.getDesktop().open(new File("C:/Users/Gezelle/Documents/MAR/" +lastName + "_" +firstName + ".xls"));
        } 
            catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
                        
    
                } catch (SQLException | IOException e) {
                    System.err.println(e);
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MainWindow().setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

     
    
    
    
      private void myComboBox(){
         try {
           
            ResultSet rs=null;
            PreparedStatement stmt=null;         
            
            stmt= con.prepareStatement("select LastName, FirstName,ClientKey, DateOfBirth   from client order by LastName");
            rs = stmt.executeQuery();            
           
           
            while (rs.next()) {
                String st1 = rs.getString(1);
                String st2 = rs.getString(2);
                jComboBox1.addItem(st1 + ", " + st2);        
                           
        } 
           
          //  jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(doc));
        }
          catch (HeadlessException | SQLException e) {
            System.err.println(e);
            //System.exit(1);
        }
    }
      
      private void dateOfBirth(){
            try {
           
            ResultSet rs=null;
            PreparedStatement stmt=null;         
            
            stmt= con.prepareStatement("select ClientKey, DateOfBirth   from client  where LastName='" + lastName + "' and FirstName='" + firstName.trim() + "'");
            rs = stmt.executeQuery();            
           
           
            while (rs.next()) {
                    dob = rs.getDate(2);
                          
        } 
          
        }
          catch (HeadlessException | SQLException e) {
            System.err.println(e);
            //System.exit(1);
        }
      }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicationRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicationRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicationRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicationRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicationRecord().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
